// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: debug_info.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DebugEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`          // 日志级别
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // 时间戳（毫秒）
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`      // 调试信息内容
	Data          *structpb.Value        `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`            // 额外数据
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugEntry) Reset() {
	*x = DebugEntry{}
	mi := &file_debug_info_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugEntry) ProtoMessage() {}

func (x *DebugEntry) ProtoReflect() protoreflect.Message {
	mi := &file_debug_info_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugEntry.ProtoReflect.Descriptor instead.
func (*DebugEntry) Descriptor() ([]byte, []int) {
	return file_debug_info_proto_rawDescGZIP(), []int{0}
}

func (x *DebugEntry) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *DebugEntry) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *DebugEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *DebugEntry) GetData() *structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

type DebugInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"` // 是否启用调试
	Parts         []*DebugEntry          `protobuf:"bytes,2,rep,name=parts,proto3" json:"parts,omitempty"`      // 多条调试信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DebugInfo) Reset() {
	*x = DebugInfo{}
	mi := &file_debug_info_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DebugInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DebugInfo) ProtoMessage() {}

func (x *DebugInfo) ProtoReflect() protoreflect.Message {
	mi := &file_debug_info_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DebugInfo.ProtoReflect.Descriptor instead.
func (*DebugInfo) Descriptor() ([]byte, []int) {
	return file_debug_info_proto_rawDescGZIP(), []int{1}
}

func (x *DebugInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *DebugInfo) GetParts() []*DebugEntry {
	if x != nil {
		return x.Parts
	}
	return nil
}

var File_debug_info_proto protoreflect.FileDescriptor

const file_debug_info_proto_rawDesc = "" +
	"\n" +
	"\x10debug_info.proto\x12\x12common.response.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x86\x01\n" +
	"\n" +
	"DebugEntry\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12*\n" +
	"\x04data\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\x04data\"[\n" +
	"\tDebugInfo\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x124\n" +
	"\x05parts\x18\x02 \x03(\v2\x1e.common.response.v1.DebugEntryR\x05partsB4Z2gitee.com/fatzeng/switch-sdk-core/resp/proto;protob\x06proto3"

var (
	file_debug_info_proto_rawDescOnce sync.Once
	file_debug_info_proto_rawDescData []byte
)

func file_debug_info_proto_rawDescGZIP() []byte {
	file_debug_info_proto_rawDescOnce.Do(func() {
		file_debug_info_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_debug_info_proto_rawDesc), len(file_debug_info_proto_rawDesc)))
	})
	return file_debug_info_proto_rawDescData
}

var file_debug_info_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_debug_info_proto_goTypes = []any{
	(*DebugEntry)(nil),     // 0: common.response.v1.DebugEntry
	(*DebugInfo)(nil),      // 1: common.response.v1.DebugInfo
	(*structpb.Value)(nil), // 2: google.protobuf.Value
}
var file_debug_info_proto_depIdxs = []int32{
	2, // 0: common.response.v1.DebugEntry.data:type_name -> google.protobuf.Value
	0, // 1: common.response.v1.DebugInfo.parts:type_name -> common.response.v1.DebugEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_debug_info_proto_init() }
func file_debug_info_proto_init() {
	if File_debug_info_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_debug_info_proto_rawDesc), len(file_debug_info_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_debug_info_proto_goTypes,
		DependencyIndexes: file_debug_info_proto_depIdxs,
		MessageInfos:      file_debug_info_proto_msgTypes,
	}.Build()
	File_debug_info_proto = out.File
	file_debug_info_proto_goTypes = nil
	file_debug_info_proto_depIdxs = nil
}
