// proto/common/response.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: response.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resp 响应结构
type Resp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// resp code
	Code *int64 `protobuf:"varint,1,opt,name=code,proto3,oneof" json:"code,omitempty"`
	// resp message
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// resp data
	Data *structpb.Value `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	// request data
	Params *structpb.Value `protobuf:"bytes,4,opt,name=params,proto3" json:"params,omitempty"`
	// resp 扩展信息
	ExtraData *structpb.Value `protobuf:"bytes,5,opt,name=extra_data,json=extraData,proto3" json:"extra_data,omitempty"`
	// 统计信息
	Statistics *Statistics `protobuf:"bytes,6,opt,name=statistics,proto3" json:"statistics,omitempty"`
	// 追踪信息
	Trace *Trace `protobuf:"bytes,7,opt,name=trace,proto3" json:"trace,omitempty"`
	// debug信息
	DebugInfo     *DebugInfo `protobuf:"bytes,8,opt,name=debug_info,json=debugInfo,proto3" json:"debug_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resp) Reset() {
	*x = Resp{}
	mi := &file_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resp) ProtoMessage() {}

func (x *Resp) ProtoReflect() protoreflect.Message {
	mi := &file_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resp.ProtoReflect.Descriptor instead.
func (*Resp) Descriptor() ([]byte, []int) {
	return file_response_proto_rawDescGZIP(), []int{0}
}

func (x *Resp) GetCode() int64 {
	if x != nil && x.Code != nil {
		return *x.Code
	}
	return 0
}

func (x *Resp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Resp) GetData() *structpb.Value {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Resp) GetParams() *structpb.Value {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *Resp) GetExtraData() *structpb.Value {
	if x != nil {
		return x.ExtraData
	}
	return nil
}

func (x *Resp) GetStatistics() *Statistics {
	if x != nil {
		return x.Statistics
	}
	return nil
}

func (x *Resp) GetTrace() *Trace {
	if x != nil {
		return x.Trace
	}
	return nil
}

func (x *Resp) GetDebugInfo() *DebugInfo {
	if x != nil {
		return x.DebugInfo
	}
	return nil
}

var File_response_proto protoreflect.FileDescriptor

const file_response_proto_rawDesc = "" +
	"\n" +
	"\x0eresponse.proto\x12\x12common.response.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x10statistics.proto\x1a\vtrace.proto\x1a\x10debug_info.proto\"\x84\x03\n" +
	"\x04Resp\x12\x17\n" +
	"\x04code\x18\x01 \x01(\x03H\x00R\x04code\x88\x01\x01\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x04data\x18\x03 \x01(\v2\x16.google.protobuf.ValueR\x04data\x12.\n" +
	"\x06params\x18\x04 \x01(\v2\x16.google.protobuf.ValueR\x06params\x125\n" +
	"\n" +
	"extra_data\x18\x05 \x01(\v2\x16.google.protobuf.ValueR\textraData\x12>\n" +
	"\n" +
	"statistics\x18\x06 \x01(\v2\x1e.common.response.v1.StatisticsR\n" +
	"statistics\x12/\n" +
	"\x05trace\x18\a \x01(\v2\x19.common.response.v1.TraceR\x05trace\x12<\n" +
	"\n" +
	"debug_info\x18\b \x01(\v2\x1d.common.response.v1.DebugInfoR\tdebugInfoB\a\n" +
	"\x05_codeB4Z2gitee.com/fatzeng/switch-sdk-core/resp/proto;protob\x06proto3"

var (
	file_response_proto_rawDescOnce sync.Once
	file_response_proto_rawDescData []byte
)

func file_response_proto_rawDescGZIP() []byte {
	file_response_proto_rawDescOnce.Do(func() {
		file_response_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_response_proto_rawDesc), len(file_response_proto_rawDesc)))
	})
	return file_response_proto_rawDescData
}

var file_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_response_proto_goTypes = []any{
	(*Resp)(nil),           // 0: common.response.v1.Resp
	(*structpb.Value)(nil), // 1: google.protobuf.Value
	(*Statistics)(nil),     // 2: common.response.v1.Statistics
	(*Trace)(nil),          // 3: common.response.v1.Trace
	(*DebugInfo)(nil),      // 4: common.response.v1.DebugInfo
}
var file_response_proto_depIdxs = []int32{
	1, // 0: common.response.v1.Resp.data:type_name -> google.protobuf.Value
	1, // 1: common.response.v1.Resp.params:type_name -> google.protobuf.Value
	1, // 2: common.response.v1.Resp.extra_data:type_name -> google.protobuf.Value
	2, // 3: common.response.v1.Resp.statistics:type_name -> common.response.v1.Statistics
	3, // 4: common.response.v1.Resp.trace:type_name -> common.response.v1.Trace
	4, // 5: common.response.v1.Resp.debug_info:type_name -> common.response.v1.DebugInfo
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_response_proto_init() }
func file_response_proto_init() {
	if File_response_proto != nil {
		return
	}
	file_statistics_proto_init()
	file_trace_proto_init()
	file_debug_info_proto_init()
	file_response_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_response_proto_rawDesc), len(file_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_response_proto_goTypes,
		DependencyIndexes: file_response_proto_depIdxs,
		MessageInfos:      file_response_proto_msgTypes,
	}.Build()
	File_response_proto = out.File
	file_response_proto_goTypes = nil
	file_response_proto_depIdxs = nil
}
